version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
    restart: always
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
#      for what?
#      - './src:/var/www/html'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'
    ports:
      - 8080:80
    restart: always

  mysql:
    image: mysql:8
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:63306:3306
    restart: always
