version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
#      for what?
#      - './src:/var/www/html'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root